/**
 * Generates the strapwork field the site uses as its ground.
 *
 * Output goes to src/data/girih.json and is imported at build time, so the
 * browser never runs any of this geometry. Straps are grouped into rings by
 * distance from the centre so the hero can draw them in radiating outward with
 * only a handful of DOM nodes.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { growTiling, strapsOf, centroid } from "./girih/tiling.js";
import type { Vec } from "./girih/tiles.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RINGS = 8;

/** Grown wider than the crop so straps run off every edge instead of stopping ragged. */
const patch = growTiling("decagon", 220, 1150);
const straps = strapsOf(patch);

const dist = (p: Vec) => Math.hypot(p[0], p[1]);
const withDist = straps
  .map((s) => ({ s, d: dist(centroid(s.points)) }))
  .sort((a, b) => a.d - b.d);

const per = Math.ceil(withDist.length / RINGS);
const rings: string[] = [];
for (let i = 0; i < RINGS; i++) {
  const slice = withDist.slice(i * per, (i + 1) * per);
  rings.push(
    slice
      .map(({ s }) => "M " + s.points.map((p) => p.map((n) => n.toFixed(1)).join(" ")).join(" L "))
      .join(" "),
  );
}

// Crop well inside the grown patch so the field reads as endless.
const reach = Math.max(...withDist.map((w) => w.d));
const half = Math.round((reach * 0.62) / 2) * 2;
const viewBox = `${-half} ${-half} ${half * 2} ${half * 2}`;

const out = {
  viewBox,
  rings: rings.filter(Boolean),
  meta: {
    tiles: patch.length,
    straps: straps.length,
    strapAngle: 54,
    note: "Generated by scripts/build-girih.ts. Tile outlines are scaffolding and are never emitted.",
  },
};

fs.mkdirSync(path.join(ROOT, "src", "data"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "src", "data", "girih.json"), JSON.stringify(out, null, 2));

const tally: Record<string, number> = {};
for (const t of patch) tally[t.name] = (tally[t.name] ?? 0) + 1;
console.log(`\n─── girih field ${"".padEnd(40, "─")}`);
console.log(`tiles placed: ${patch.length}`, tally);
console.log(`straps: ${straps.length}  →  ${out.rings.length} rings`);
console.log(`viewBox: ${viewBox}`);
console.log(`size: ${(JSON.stringify(out).length / 1024).toFixed(1)} KB\n`);
